context:
  name: shs-cassini-headers
  version: "12.0.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/HewlettPackard/shs-cassini-headers/archive/refs/tags/release/shs-${{ version }}.tar.gz
    sha256: 5ad3353e93d9e881a3eeaec8349d5c94e13ea5b6cf22556015f0e6454fba77ed  # Tagged release 12.0.1, aligns with spec version 1.1.1

build:
  number: 0
  noarch: generic
  script: build.sh

tests:
  - script:
      - test -f ${PREFIX}/include/sbl/sbl_pml.h
      - test -f ${PREFIX}/share/cassini-headers/csr_defs.json

about:
  homepage: https://github.com/HewlettPackard/shs-cassini-headers
  repository: https://github.com/HewlettPackard/shs-cassini-headers
  license: GPL-2.0-or-later OR BSD-3-Clause  # Dual license from cray-cassini-headers-public.spec
  license_file: cray-cassini-headers-public.spec
  summary: 'Headers for Cassini (Slingshot) interconnect'
  description: |
    Provides headers and shared data (e.g., JSON definitions) for Cassini-based systems.
    Dual-licensed under GPL-2.0-or-later or BSD-3-Clause as per cray-cassini-headers-public.spec.

extra:
  recipe-maintainers:
    - j34ni
